version: 2.1

orbs:
  node: circleci/node@5.1
  coveralls: kaze/coveralls@1.0.1

jobs:
  cov-korean:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Generate coverage
          command: npx nx run @romanize/korean:coverage
      - coveralls/upload:
          parallel: true
          path_to_lcov: ./packages/korean/coverage/lcov.info
          flag_name: Korean
          verbose: true
          filepath: ./packages/korean/
  cov-done:
    docker:
      - image: cimg/node:16.10
    steps:
      - coveralls/upload:
          parallel_finished: true
  deploy-korean:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Deploy to NPM
          command: npx nx run @romanize/korean:publish

workflows:
  cov-gen:
    jobs:
      - cov-korean:
          filters:
            branches:
              only:
                - main
      - cov-done:
          requires:
            - cov-korean
          filters:
            branches:
              only:
                - main
  npm-korean:
    jobs:
      - deploy-korean:
          filters:
            branches:
              only:
                - main
