version: 2.1

orbs:
  node: circleci/node@5.1
  coveralls: coveralls/coveralls@1.0.6

jobs:
  cov-korean:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Generate coverage
          command: npx nx run @romanize/korean:coverage
      - coveralls/upload:
          parallel: true
          path_to_lcov: ./packages/korean/coverage/lcov.info
          flag_name: Korean
  cov-done:
    docker:
      - image: cimg/node:16.10
    steps:
      - coveralls/upload:
          parallel_finished: true

workflows:
  cov-gen:
    jobs:
      - cov-korean
      - cov-done:
          requires: 
            - cov-korean
