on:
  push:
    branches:
      - main

name: Publish package to NPM

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - korean
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: npm install
      run: npm install
    - name: Deploy to NPM
      run: npx nx run @romanize/${{ matrix.project }}:deploy